spring:
  application:
    name: mail-service

  mail:
    alias: "Testing Spring Boot"
    unsupportedHtmlRenderText: "You should open this mail which support html rendering! eg. Gmail, Outlook"
    host: smtp.gmail.com
    port: 587
    username: kyawzayar.ht@gmail.com
    password: bicuokyzvetovgxn
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mail_service

server:
  port: 8081